package com.group213.vet.app.model;

public enum ERole {
    ROLE_USER,
    ROLE_ADMIN,
    ROLE_TEACHING_TECHNICIAN,
    ROLE_ANIMAL_HEALTH_TECHNICIAN,
    ROLE_STUDENT,
    ROLE_ANIMAL_CARE_ATTENDANT
}
